  # Prefix of all death messages
  prefix: ""
  # Suffix of all death messages
  suffix: ""
  # If you want a prefix / suffix only for PVP messages, uncomment these:
  # prefix-pvp: ""
  # suffix-pvp: ""
  mob:
    Bat:
      - "%&cplrtag% &7tapeti &eNahkhiire &7poolt"
    BlazeMelee:
      - "&c%plrtag% &7tapeti &eBlazi &7poolt"
    BlazeFireball:
      - "&c%plrtag% &7rünnati tulepallidega &eBlazi &7poolt"
    CaveSpider:
      - "&c%plrtag% &7rünnati &e&lKoopa Ämbliku &7poolt"
    Chicken:
      - "&c%plrtag% &7rünnati &eKana &7poolt"
    Cow:
      - "&c%plrtag% &7rünnati &eLehma &7poolt"
    Creeper:
      - "&c%plrtag% &7lasti õhku &eCreeperi &7poolt"
    Donkey:
      - "&c%plrtag% &7rünnati &eEesli &7poolt"
    ElderGuardian:
      - "&c%plrtag% &7tapeti &eElder Guardiani &7poolt"
    EnderDragon:
      - "&c%plrtag% &7tapeti &eEnder Dragoni &7poolt"
    EnderDragonBreath:
      - "%plrtag% was roasted in dragon breath"
    Enderman:
      - "&c%plrtag% &7rünnati &eEndermani &7poolt"
    Endermite:
      - "&c%plrtag% &7tapeti &eEndermitei &7poolt"
    Evoker:
      - "&c%plrtag% &7tapeti &eEvokeri &7poolt"
    Ghast:
      - "&c%plrtag% &7rünnati tulepallidega &eGhasti &7poolt"
    Giant:
      - "&c%plrtag% &7tapeti &eGianti &7poolt"
    Guardian:
      - "&c%plrtag% &7tapeti &eGuardiani &7poolt"
    Horse:
      - "&c%plrtag% &7tapeti &eHobuse &7poolt"
    HuskMelee:
      - "&c%plrtag% &7tapeti &eHuski &7poolt"
    HuskCustom:
      - "%plrtag% was slain by Husk using [%weapon%&f]"
    Illusioner:
      - "%plrtag% was shot by Illusioner"
    IronGolem:
      - "&c%plrtag% &7tapeti &eIron Golemi &7poolt"
    Llama:
      - "&c%plrtag% &7tapeti &eLlama &7poolt"
    MagmaCube:
      - "&c%plrtag% &7tapeti &eMagma Cube &7poolt"
    Mooshroom:
      - "&c%plrtag% &7tapeti &eMooshroomi &7poolt"
    Mule:
      - "&c%plrtag% &7tapeti &eMule &7poolt"
    Parrot:
      - "&c%plrtag% &7tapeti &ePapagoi &7poolt"
    Pig:
      - "&c%plrtag% &7tapeti &eSea &7poolt"
    PolarBear:
      - "&c%plrtag% &7tapeti &eJääkaru &7poolt"
    Rabbit:
      - "&c%plrtag% was slain by Rabbit"
    Sheep:
      - "%plrtag% was slain by Sheep"
    Shulker:
      - "%plrtag% was slain by Shulker"
    Silverfish:
      - "%plrtag% was slain by Silverfish"
    SkeletonArrow:
      - "%plrtag% was shot by Skeleton"
    SkeletonMelee:
      - "%plrtag% was slain by Skeleton"
    SkeletonCustom:
      - "%plrtag% was slain by Skeleton using [%weapon%&f]"
    SkeletonHorse:
      - "%plrtag% was slain by Skeleton Horse"
    Slime:
      - "%plrtag% was slain by Slime"
    SnowGolem:
      - "%plrtag% was pummeled by Snow Golem"
    Spider:
      - "%plrtag% was slain by Spider"
    Squid:
      - "%plrtag% was slain by Squid"
    StrayArrow:
      - "%plrtag% was shot by Stray"
    StrayMelee:
      - "%plrtag% was slain by Stray"
    StrayCustom:
      - "%plrtag% was slain by Stray using [%weapon%&f]"
    Vex:
      - "%plrtag% was slain by Vex"
    Vindicator:
      - "%plrtag% was slain by Vindicator"
    Witch:
      - "%plrtag% was killed by Witch using magic"
    Wither:
      - "%plrtag% was slain by Wither"
    WitherSpawnBoom: # Dies from wither spawn explosion
      - "%plrtag% was blown up by Wither"
    WitherSkeletonMelee:
      - "%plrtag% was slain by Wither Skeleton"
    Wolf:
      - "%plrtag% was slain by Wolf"
    ZombieMelee:
      - "%plrtag% was slain by Zombie"
    ZombieCustom:
      - "%plrtag% was slain by Zombie using [%weapon%&f]"
    ZombiePigManMelee:
      - "%plrtag% was slain by Zombie Pigman"
    ZombiePigManCustom:
      - "%plrtag% was slain by Zombie Pigman using [%weapon%&f]"
    ZombieVillagerMelee:
      - "%plrtag% was slain by Zombie Villager"
    ZombieVillagerCustom:
      - "%plrtag% was slain by Zombie Villager using [%weapon%&f]"
    ZombieHorse:
      - "%plrtag% was slain by Zombie Horse"
  namedmob: # For named mobs, use %killer% as mob
    Bat:
      - "%plrtag% was slain by %killer%"
    BlazeMelee:
      - "%plrtag% was slain by %killer%"
    BlazeFireball:
      - "%plrtag% was fireballed by %killer%"
    CaveSpider:
      - "%plrtag% was slain by %killer%"
    Chicken:
      - "%plrtag% was slain by %killer%"
    Cow:
      - "%plrtag% was slain by %killer%"
    Creeper:
      - "%plrtag% was blown up by %killer%"
    Donkey:
      - "%plrtag% was slain by %killer%"
    ElderGuardian:
      - "%plrtag% was slain by %killer%"
    EnderDragon:
      - "%plrtag% was slain by %killer%"
    EnderDragonBreath:
      - "%plrtag% was killed by %killer% using magic"
    Enderman:
      - "%plrtag% was slain by %killer%"
    Endermite:
      - "%plrtag% was slain by %killer%"
    Evoker:
      - "%plrtag% was slain by %killer%"
    Ghast:
      - "%plrtag% was fireballed by %killer%"
    Giant:
      - "%plrtag% was slain by %killer%"
    Guardian:
      - "%plrtag% was slain by %killer%"
    Horse:
      - "%plrtag% was slain by %killer%"
    HuskMelee:
      - "%plrtag% was slain by %killer%"
    HuskCustom:
      - "%plrtag% was slain by %killer% using [%weapon%&f]"
    Illusioner:
      - "%plrtag% was shot by %killer%"
    IronGolem:
      - "%plrtag% was slain by %killer%"
    Llama:
      - "%plrtag% was slain by %killer%"
    MagmaCube:
      - "%plrtag% was slain by %killer%"
    Mooshroom:
      - "%plrtag% was slain by %killer%"
    Mule:
      - "%plrtag% was slain by %killer%"
    Parrot:
      - "%plrtag% was slain by %killer%"
    Pig:
      - "%plrtag% was slain by %killer%"
    PolarBear:
      - "%plrtag% was slain by %killer%"
    Rabbit:
      - "%plrtag% was slain by %killer%"
    Sheep:
      - "%plrtag% was slain by %killer%"
    Shulker:
      - "%plrtag% was slain by %killer%"
    Silverfish:
      - "%plrtag% was slain by %killer%"
    SkeletonArrow:
      - "%plrtag% was shot by %killer%"
    SkeletonMelee:
      - "%plrtag% was slain by %killer%"
    SkeletonCustom:
      - "%plrtag% was slain by %killer% using [%weapon%&f]"
    SkeletonHorse:
      - "%plrtag% was slain by %killer%"
    Slime:
      - "%plrtag% was slain by %killer%"
    SnowGolem:
      - "%plrtag% was pummeled by %killer%"
    Spider:
      - "%plrtag% was slain by %killer%"
    Squid:
      - "%plrtag% was slain by %killer%"
    StrayArrow:
      - "%plrtag% was shot by %killer%"
    StrayMelee:
      - "%plrtag% was slain by %killer%"
    StrayCustom:
      - "%plrtag% was slain by %killer% using [%weapon%&f]"
    Vex:
      - "%plrtag% was slain by %killer%"
    Villager:
      - "%plrtag% was slain by %killer%"
    Vindicator:
      - "%plrtag% was slain by %killer%"
    Witch:
      - "%plrtag% was killed by %killer% using magic"
    Wither:
      - "%plrtag% was slain by %killer%"
    WitherSpawnBoom: # Dies from wither spawn explosion
      - "%plrtag% was blown up by %killer%"
    WitherSkeletonMelee:
      - "%plrtag% was slain by %killer%"
    WitherSkeletonCustom:
      - "%plrtag% was slain by %killer% using [%weapon%&f]"
    Wolf:
      - "%plrtag% was slain by %killer%"
    ZombieMelee:
      - "%plrtag% was slain by %killer%"
    ZombieCustom:
      - "%plrtag% was slain by %killer% using [%weapon%&f]"
    ZombiePigManMelee:
      - "%plrtag% was slain by %killer%"
    ZombiePigManCustom:
      - "%plrtag% was slain by %killer% using [%weapon%&f]"
    ZombieVillagerMelee:
      - "%plrtag% was slain by %killer%"
    ZombieVillagerCustom:
      - "%plrtag% was slain by %killer% using [%weapon%&f]"
    ZombieHorse:
      - "%plrtag% was slain by %killer%"
  pvp:
    PlayerMelee:
      - "%plrtag% was slain by %killer%"
    PlayerCustom:
      - "%plrtag% was slain by %killer% using [%weapon%&f]"
    PlayerArrow:
      - "%plrtag% was shot by %killer%"
    PlayerFireball: # Just in case
      - "%plrtag% was fireballed by %killer%"
    PlayerSnowball: # Just in case
      - "%plrtag% was pummeled by %killer%"
    PlayerProjectileCustom: # Bows, plugins like CrackShot
      - "%plrtag% was shot by %killer% using [%weapon%&f]"
    PlayerPotion:
      - "%plrtag% was killed by %killer% using magic"
  natural:
    Thorns:
      - "%plrtag% was killed while trying to hurt %killer%"
    TNT:
      - "%plrtag% blew up"
    TNTKill:
      - "%plrtag% was blown up by %killer%"
    EnderCrystal:
      - "%plrtag% blew up"
    Bed: # exploding beds
      - "%plrtag% blew up"
    Cactus:
      - "%plrtag% was pricked to death"
    CactusKill:
      - "%plrtag% walked into a cactus whilst trying to escape %killer%"
    Anvil:
      - "%plrtag% was squashed by a falling anvil"
    FallingBlock: # Only when a FallingBlock is modified to cause damage
      - "%plrtag% was squashed by a falling block"
    UnknownArrow: # arrow from unknown entity or source, /summon?
      - "&c%plrtag% &7rünnati &enoolega"
    DispenserArrow:
      - "%plrtag% was shot by arrow"
    DispenserFireball:
      - "%plrtag% burned to death"
    DispenserSnowball:
      - "%plrtag% died"
    Drowning:
      - "%plrtag% drowned"
    DrowningKill:
      - "%plrtag% drowned whilst trying to escape %killer%"
    PotionPoison: # Normally impossible
      - "%plrtag% died"
    PotionWither:
      - "%plrtag% withered away"
    PotionHarming:
      - "%plrtag% was killed by magic"
    FireBlock:
      - "%plrtag% went up in flames"
    FireBlockKill:
      - "%plrtag% walked into a fire whilst fighting %killer%"
    FireTick:
      - "%plrtag% burned to death"
    FireTickKill:
      - "%plrtag% burnt into a crisp whilst fighting %killer%"
    Magma:
      - "&c%plrtag% &7avastas, et põrand on &eLaava"
    MagmaKill:
      - "%plrtag% walked into danger zone due to %killer%"
    Lava:
      - "&c%plrtag% &7üritas ujuda &eLaavas"
    LavaKill:
      - "%plrtag% tried to swim in lava while trying to escape %killer%"
    Lightning: # Happens when struck by lightning, vanilla: FireTick/FireBlock
      - "%plrtag% went up in flames"
    Starvation:
      - "%plrtag% starved to death"
    Suffocation:
      - "%plrtag% suffocated in a wall"
    Cramming: # maxEntityCramming
      - "%plrtag% was squished too much"
    CrammingKill:
      - "%plrtag% was squished too much"
    Void:
      - "%plrtag% fell out of the world"
    VoidFall: # in DMP, if entity falls over y>=64 to the void
      - "%plrtag% fell from a high place and fell out of the world"
    VoidKill:
      - "%plrtag% was knocked into the void by %killer%"
    FallShort: # Fall distance 5 blocks or less, or ender pearl
      - "%plrtag% hit the ground too hard"
    FallLong: # Fall distance over 5 blocks
      - "%plrtag% fell from a high place"
    FallLadder:
      - "%plrtag% fell off a ladder"
    FallVine:
      - "%plrtag% fell off some vines"
    FallWater:
      - "%plrtag% out of the water"
    FallFire:
      - "%plrtag% fell into a patch of fire"
    FallCacti:
      - "%plrtag% fell into a patch of cacti"
    FallKill:
      - "%plrtag% was doomed to fall by %killer%"
    FallKillWeapon:
      - "%plrtag% was doomed to fall by %killer% using [%weapon%&f]"
    FallFinishKill:
      - "%plrtag% fell too far and was finished by %killer%"
    FallFinishKillWeapon:
      - "%plrtag% fell too far and was finished by %killer% using [%weapon%&f]"
    FallExplosionKill: # FallKill caused by entity explosion
      - "%plrtag% was blown from a high place by %killer%"
    FallLadderKill:
      - "%plrtag% was shot off a ladder by %killer%"
    FallVineKill:
      - "%plrtag% was shot off some vines by %killer%"
    Firework:
      - "%plrtag% went off with a bang"
    Elytra:
      - "%plrtag% &clendamise jõud sai otsa ning ta kukkus alla&8."
    Suicide: # Some plugins may use this one, /suicide and /kill for example
      - "%plrtag% &csooritas enesetapu&8."
    Melting: # Some plugins may use this one, orig. Snowmans + hot biomes
      - "%plrtag% died"
    Custom: # Some plugins may use this one
      - "%plrtag% died"

